# Generated by Django 3.2.7 on 2022-09-05 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.UUIDField(default=uuid.uuid4, help_text='API key for use in Zapier integration')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the token was created.')),
                ('refreshed_at', models.DateTimeField(blank=True, default=None, help_text='When the token was last refreshed.', null=True)),
                ('revoked_at', models.DateTimeField(blank=True, default=None, help_text='When the token was last revoked.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='True if the token can be used.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zapier_token', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TokenAuthRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_requests', to='authtoken.authtoken')),
            ],
            options={
                'get_latest_by': 'timestamp',
            },
        ),
    ]
