# Generated by Django 4.1.1 on 2022-09-05 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authtoken", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="authtoken",
            name="is_active",
        ),
    ]
