# Generated by Django 4.0.2 on 2022-07-01 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zapier", "0002_add_tokenauthrequest"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="zapiertokenrequest",
            options={"get_latest_by": "timestamp"},
        ),
        migrations.RenameModel(
            old_name="ZapierTokenRequest",
            new_name="PollingTriggerRequest",
        ),
    ]
