# Generated by Django 4.0.5 on 2022-07-03 10:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("zapier", "0003_rename_zapiertokenrequest_pollingtriggerrequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="RestHookSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scope", models.CharField(blank=True, db_index=True, max_length=50)),
                (
                    "target_url",
                    models.URLField(
                        help_text="The webhook URL to which any payload will be POSTed."
                    ),
                ),
                (
                    "subscribed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Timestamp marking when the initial subscribe event occurred.",
                    ),
                ),
                (
                    "unsubscribed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Timestamp marking when the unsubscribe event occurred.",
                    ),
                ),
                (
                    "token",
                    models.ForeignKey(
                        help_text="The ZapierToken against which to store the webhook.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zapier.zapiertoken",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
