# Generated by Django 4.0.5 on 2022-08-08 19:56

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("zapier", "0004_resthooksubscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="resthooksubscription",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, help_text="Public ID"),
        ),
        migrations.AlterField(
            model_name="resthooksubscription",
            name="token",
            field=models.ForeignKey(
                help_text="The ZapierToken against which to store the webhook.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="webhooks",
                to="zapier.zapiertoken",
            ),
        ),
        migrations.AlterField(
            model_name="resthooksubscription",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rest_hooks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
