# Generated by Django 4.0.5 on 2022-08-08 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zapier", "0005_resthooksubscription_uuid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resthooksubscription",
            name="scope",
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="resthooksubscription",
            name="unsubscribed_at",
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text="Timestamp marking when the unsubscribe event occurred.",
                null=True,
            ),
        ),
    ]
