# Generated by Django 4.1.1 on 2022-09-06 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hooks", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resthookevent",
            name="response_payload",
        ),
    ]
