# Generated by Django 4.1.1 on 2022-09-06 12:13

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hooks", "0002_remove_resthookevent_response_payload"),
    ]

    operations = [
        migrations.AddField(
            model_name="resthookevent",
            name="response_payload",
            field=models.JSONField(
                blank=True,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                null=True,
            ),
        ),
    ]
