# Generated by Django 4.1 on 2022-09-03 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authtoken", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tokenauthrequest",
            name="token",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="auth_requests",
                to="authtoken.authtoken",
            ),
        ),
    ]
