# Generated by Django 4.1.1 on 2022-09-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polling", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pollingtriggerrequest",
            name="last_object_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The id of the most recent object returned to Zapier (will be empty if no data was returned in this response).",
                max_length=100,
            ),
        ),
    ]
